### PR TITLE
Update ResidentAIDetour.cs

### PR DESCRIPTION
**Pull request by gawrbage**
i cut yo dumb ''obi'' crap and removed impossible to reach code.

### CODE REVIEW

**Comment by bloodypenguin** [comment]
I will look into impossible to reach code. But I will not merge this because the lines you call dumb crap are actually there for purpose. If detour fails I will see those dumb lines in my output log.

**Comment by bloodypenguin** [comment]
Please don't be rude

**Comment by gawrbage** [comment]
I thought this mod was dead because i havent had a reply in 2 months. Anyway good luck in developing your mods.

**Comment by bloodypenguin** [comment]
@gawrbage Actually that code is totally reachable. UpdateHealth() and UpdateAge() methods take citizen's data by reference and may set the Dead flag if the citizen should die of bad health / old age, respectively.

**Pull request closed without merging**
